# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- cd Example 
- pod install 
- cd ..
#- set -o pipefail && xcodebuild -workspace Example/SEUIKit.xcworkspace -scheme SEUIKit-Example -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty
- pod lib lint
